# Generated by Django 4.1.7 on 2023-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('language', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('hotel_name', models.CharField(max_length=255)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('tours', models.TextField()),
                ('num_adults', models.IntegerField()),
                ('num_children_5_12', models.IntegerField(blank=True, null=True)),
                ('num_children_0_4', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
