# Generated by Django 4.1.7 on 2023-03-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_reservation_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='hotel_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='language',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='num_adults',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='num_children_0_4',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='num_children_5_12',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='tours',
        ),
    ]
