# Generated by Django 4.1.7 on 2023-03-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_reservation_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='mobile_number',
            field=models.CharField(default='123456789', max_length=20),
        ),
    ]
