# Generated by Django 4.1.7 on 2023-03-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_reservation_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='mobile_number',
            new_name='phone_number',
        ),
    ]
